# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoKasInsumos
                                 A QGIS plugin
 GeoKas Insumos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-03-27
        git sha              : $Format:%H$
        copyright            : (C) 2025 by GeoKas
        email                : contacto@geokas.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QUrl, Qt
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction, QComboBox, QCheckBox, QTableWidgetItem  # Add import for QComboBox, QCheckBox, and QTableWidgetItem
from qgis.core import QgsRasterLayer, QgsProject, QgsWkbTypes, QgsCoordinateTransform, QgsCoordinateReferenceSystem, QgsPointXY  # Import QgsRasterLayer, QgsProject, QgsWkbTypes, QgsCoordinateTransform, QgsCoordinateReferenceSystem, and QgsPointXY

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .GeoKasInsumos_dialog import GeoKasInsumosDialog
from .GeoKasInsumos_dialog_2 import GeoKasInsumosDialog_2, GeoKasInsumosDockableDialog2
from .GeoKasInsumos_dialog_3 import GeoKasInsumosDialog_3, GeoKasInsumosDockableDialog3
import os.path
import os
from qgis.PyQt.QtWidgets import QFrame
from qgis.PyQt.QtWebKitWidgets import QWebView
import requests
from datetime import datetime
from qgis.core import QgsGeometry
from qgis.gui import QgsRubberBand, QgsMapTool  # Import QgsRubberBand and QgsMapTool
from qgis.utils import iface


rb=QgsRubberBand(iface.mapCanvas(),QgsWkbTypes.PointGeometry )
rl=QgsRubberBand(iface.mapCanvas(),QgsWkbTypes.LineGeometry )
premuto= False
linea=False
point0=iface.mapCanvas().getCoordinateTransform().toMapCoordinates(0, 0)
point1=iface.mapCanvas().getCoordinateTransform().toMapCoordinates(0, 0)


class GeoKasInsumos:
    """QGIS Plugin Implementation."""


    license_file = os.path.join(os.path.dirname(os.path.realpath(__file__)), "license.txt")
    view_configuration_file = os.path.join(os.path.dirname(os.path.realpath(__file__)), "view_configuration.txt")
    ui_confuration_active = False
    array_insumos = []
    array_aoi = []
    array_rubber_bands = []
    array_xyzs = []
    license_key = ""
    array_views_insumos = []
    actual_src = ""
    json_response = ""

    base_url="http://127.0.0.1:3000"

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GeoKasInsumos_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GeoKas Insumos')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.actual_src = self.iface.mapCanvas().mapSettings().destinationCrs().authid()
        self.iface.mapCanvas().destinationCrsChanged.connect(self.on_project_crs_changed)

        self.checkbox_references = []  # Store references to QCheckBox objects

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate('GeoKasInsumos', message)
    
    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # Create a new toolbar for the plugin
        self.toolbar = self.iface.addToolBar("GeoKas Insumos")
        self.toolbar.setObjectName("GeoKasInsumosToolbar")

        icon_path = ':/plugins/GeoKasInsumos/icon.png'

        current_directory = os.path.dirname(os.path.realpath(__file__))
        eye_path = current_directory + "/icon_eye.png"

        self.add_action(
            eye_path,
            text=self.tr(u'Visualizar Insumos'),
            callback=self.viewInsumos,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False  # Do not add to default toolbar
        )

        self.toolbar.addAction(
            self.actions[-1]
        )  # Add the action to the custom toolbar

        

        # Add combo box to the custom toolbar
        self.combo_box = QComboBox(self.iface.mainWindow())
        self.combo_box.currentTextChanged.connect(self.cambioComboBoxZona)
        self.toolbar.addWidget(self.combo_box)

        self.check_box = QCheckBox(self.iface.mainWindow())
        self.check_box.setText("Mostrar AOI's")
        self.check_box.stateChanged.connect(self.cambioMostrarAOI)
        self.toolbar.addWidget(self.check_box)


        self.combo_box2 = QComboBox(self.iface.mainWindow())
        self.combo_box2.currentTextChanged.connect(self.cambioComboBoxXYZ)
        self.toolbar.addWidget(self.combo_box2)

        self.check_license()

        configure_path = current_directory + "/icon_setting.png"

        self.add_action(
            configure_path,
            text=self.tr(u'Configurar Insumos'),
            callback=self.configure,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False  # Do not add to default toolbar
        )

        self.toolbar.addAction(
            self.actions[-1]
        )  # Add the action to the custom toolbar

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item, icon, and custom toolbar from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GeoKas Insumos'),
                action)
            self.iface.removeToolBarIcon(action)

        # Remove custom toolbar and its widgets
        if hasattr(self, 'toolbar'):
            self.toolbar.clear()  # Clear all widgets and actions from the toolbar
            self.iface.mainWindow().removeToolBar(self.toolbar)  # Remove the toolbar from the main window
            self.toolbar = None
    
    def on_project_crs_changed(self):
        """Handle changes to the project's coordinate reference system (CRS)."""
        new_crs = self.iface.mapCanvas().mapSettings().destinationCrs().authid()
        self.actual_src = new_crs

    def cambioComboBoxZona(self, text):
        print("Opcion seleccionada: "+text)
        index = next((i for i, item in enumerate(self.array_aoi) if item["nombre"] == text), -1)
        if index != -1:
            print(f"Index found: {index}")
            try:
                geometry_aoi = QgsGeometry.fromWkt(self.array_aoi[index]["geometry"])

                print("Geometry created successfully")
                if geometry_aoi.isEmpty():
                    print("Geometry is empty")
                else:
                    print("Geometry created successfully")
                    extent_aoi = geometry_aoi.boundingBox()
                    self.iface.mapCanvas().setExtent(extent_aoi)
                    self.iface.mapCanvas().refresh()
                    # Perform operations with the geometry here
            except Exception as e:
                print(f"Error creating geometry: {e}")
        else:
            print("Value not found")
    
    def cambioComboBoxXYZ(self, text):
        print("Opcion seleccionada: "+text)


        index = next((i for i, item in enumerate(self.array_xyzs) if item["nombre"] == text), -1)
        if index != -1 and index!=0:
            print(f"Index found: {index}")
            layer = QgsRasterLayer(
                "type=xyz&url="+self.array_xyzs[index]["url"]+"?token="+self.license_key+"&zmax="+str(self.array_xyzs[index]["zmax"]),
                self.array_xyzs[index]["nombre"],
                "wms"
            )
            if not layer.isValid():
                print("Failed to load "+self.array_xyzs[index]["nombre"]+" layer")
            else:
                QgsProject.instance().addMapLayer(layer)
        else:
            print("Value not found")




        if text == "XYZ Jamundi":
            layer = QgsRasterLayer(
                "type=xyz&url=https://xyz-jamundi.geokas.com.co/Z{z}/{y}/{X}.jpg?token=asbdasjdbas&zmax=23",
                "XYZ Jamundi",
                "wms"
            )
            if not layer.isValid():
                print("Failed to load XYZ Jamundi layer")
            else:
                QgsProject.instance().addMapLayer(layer)
        elif text == "XYZ Bruselas":
            layer = QgsRasterLayer(
                "type=xyz&url=https://2d-bruselas-pit-col.falconprecision.co/Z{z}/{y}/{X}.png?token=asbdasjdbas&zmax=23",
                "XYZ Bruselas",
                "wms"
            )
            if not layer.isValid():
                print("Failed to load XYZ Bruselas layer")
            else:
                QgsProject.instance().addMapLayer(layer)

    def on_license_changed(self):
        if len(self.dlg.lineEditLicencia.text()) > 0:
            self.dlg.buttonVerificar.setEnabled(True)
        else:
            self.dlg.buttonVerificar.setEnabled(False)

    def button_verificar_clicked(self):
        if self.ui_confuration_active:
            print("*****Iniciando request")

            self.dlg.labelNombreLicencia.setText("Verificando licencia...")
            
            self.dlg.labelCliente.setText("")

            self.dlg.labelDuracionLicencia.setText("")

            self.dlg.lineEditLicencia.setEnabled(False)
            self.dlg.buttonVerificar.setEnabled(False)
            
            self.dlg.repaint()

            self.write_license()

    def cambioMostrarAOI(self, state):
        if state == 2:
            print("State changed: " + str(state))

            for rubber_band in self.array_rubber_bands:
                rubber_band.show()

        elif state == 0:
            print("State changed: " + str(state))

            for rubber_band in self.array_rubber_bands:
                rubber_band.hide()

    def viewInsumos(self):
        tool = PointTool(self.iface, self.iface.mapCanvas(), self.base_url, self.license_key, self.array_insumos, self.array_rubber_bands, self.json_response)
        
        self.iface.mapCanvas().setMapTool(tool)

        """

        array_paso_activos = []

        # Check the view_configuration_file for active items
        if os.path.exists(self.view_configuration_file):
            with open(self.view_configuration_file, 'r') as file:
                for line in file:
                    if "Active" in line:
                        array_paso_activos.append(line.split(":")[0].strip())
        


        for i in range(len(self.array_insumos)):
            if str(self.array_insumos[i]["id"])+"-"+str(self.array_insumos[i]["tipo"]) in array_paso_activos:
                if self.array_insumos[i]["vista"] == "" or self.array_insumos[i]["vista"] == None:
                    self.array_insumos[i]["vista"] = GeoKasInsumosDockableDialog2()
                    self.array_insumos[i]["vista"].setWindowTitle(self.array_insumos[i]["nombre"]+" - "+self.array_insumos[i]["tipo"])

                    web_view = QWebView()
                    web_view.setUrl(QUrl(self.array_insumos[i]["url"]))
                    # Remove all widgets from the container before adding a new one
                    while self.array_insumos[i]["vista"].dialog_widget.contenedor.count() > 0:
                        widget_to_remove = self.array_insumos[i]["vista"].dialog_widget.contenedor.takeAt(0).widget()
                        if widget_to_remove is not None:
                            widget_to_remove.deleteLater()
                    # Add the new widget
                    self.array_insumos[i]["vista"].dialog_widget.contenedor.addWidget(web_view)
                    self.iface.mainWindow().addDockWidget(Qt.RightDockWidgetArea, self.array_insumos[i]["vista"])
                    self.array_insumos[i]["vista"].show()
                else:
                    print("Actualizando vista existente con nombre "+self.array_insumos[i]["nombre"]+"-"+self.array_insumos[i]["tipo"])
                    web_view = QWebView()
                    web_view.setUrl(QUrl(self.array_insumos[i]["url"]))
                    # Remove all widgets from the container before adding a new one
                    while self.array_insumos[i]["vista"].dialog_widget.contenedor.count() > 0:
                        widget_to_remove = self.array_insumos[i]["vista"].dialog_widget.contenedor.takeAt(0).widget()
                        if widget_to_remove is not None:
                            widget_to_remove.deleteLater()
                    # Add the new widget
                    self.array_insumos[i]["vista"].dialog_widget.contenedor.addWidget(web_view)
        for insumo in self.array_insumos:
            print(str(str(insumo["id"])+"-"+insumo["tipo"])+"notnull" if insumo["checkbox"] is not None else str(str(insumo["id"])+"-"+insumo["tipo"])+"null")
        
        """

    def write_license(self):
        if not os.path.exists(self.license_file):
            # Si el archivo no existe, lo creamos y escribimos algo en él
            with open(self.license_file, 'w') as file:
                file.write(self.dlg.lineEditLicencia.text())
        else:
            # Si el archivo ya existe, lo leemos
            with open(self.license_file, 'r') as file:
                content = file.read()
            if content != self.dlg.lineEditLicencia.text():
                os.remove(self.license_file)
                with open(self.license_file, 'w') as file:
                    file.write(self.dlg.lineEditLicencia.text())
        self.check_license()

    def check_license(self):
        """
        Check if the license file exists and read its content.
        If the license is valid, enable the checkboxes and set the labels.
        If the license is invalid, disable the checkboxes and clear the labels.
        """


        url_restante_licencia="/api/plugins/insumos/check-license?token="
        self.license_key=""
        self.array_rubber_bands = []
        self.array_aoi = []
        self.array_aoi.append({"nombre": "Ir a...", "geometry": ""})
        self.array_xyzs = []
        self.array_xyzs.append({"nombre": "Agregar Basemap...", "url": "", "zmax": ""})
        if os.path.exists(self.license_file):
            with open(self.license_file, 'r') as file:
                content = file.read()
                self.license_key = content
                # TODO: Eliminar caracteres extras adelante y atras de la licencia
                
            try:
                response = requests.get(self.base_url+url_restante_licencia+self.license_key, timeout=60)
                license_data = response.json()
                self.json_response= license_data
                #FIXME: Solucionar cuando no hay servidor activo
                if response.status_code == 200:

                    self.iface.messageBar().pushSuccess(
                        "Validado",
                        "Licencia verificada correctamente",
                    )

                    #self.array_insumos = []

                    count_3ds_non_empty = sum(1 for proyecto in license_data["data"]["licencia"]["proyectos"] for insumo_3d in proyecto["3ds"] if insumo_3d["id"] != "")
                    count_360s_non_empty = sum(1 for proyecto in license_data["data"]["licencia"]["proyectos"] for insumo_360 in proyecto["360s"] if insumo_360["id"] != "")

                    if count_3ds_non_empty + count_360s_non_empty == 0:
                        self.array_insumos = []
                    else:

                        for insumo in self.array_insumos:
                            print(f"id: {insumo['id']}, tipo: {insumo['tipo']}, nombre: {insumo['nombre']}")

                        for proyecto in license_data["data"]["licencia"]["proyectos"]:

                            for insumo_3d in proyecto["3ds"]:
                                if len(self.array_insumos)>0:
                                    if any(insumo["id"] == insumo_3d["id"] and insumo["tipo"] == "Modelo 3D" for insumo in self.array_insumos):
                                        print("No se agregó el insumo "+insumo_3d["nombre"]+"-Modelo 3D"+" porque ya existe")
                                        continue
                                    else:
                                        checkbox = QCheckBox()
                                        checkbox.setStyleSheet("margin:auto;")
                                        checkbox.stateChanged.connect(self.insumo_seleccionado)
                                        new_insumo = {"nombre": insumo_3d["nombre"], "tipo": "Modelo 3D", "fecha": str(datetime.fromisoformat(insumo_3d["created_at"].replace("Z", "-05:00"))), "url": insumo_3d["url"], "id": insumo_3d["id"], "vista" : "", "checkbox" : checkbox}
                                        self.array_insumos.append(new_insumo)
                                        print("Se agregó el insumo "+insumo_3d["nombre"]+"-Modelo 3D")
                                else:
                                    checkbox = QCheckBox()
                                    checkbox.setStyleSheet("margin:auto;")
                                    checkbox.stateChanged.connect(self.insumo_seleccionado)
                                    new_insumo = {"nombre": insumo_3d["nombre"], "tipo": "Modelo 3D", "fecha": str(datetime.fromisoformat(insumo_3d["created_at"].replace("Z", "-05:00"))), "url": insumo_3d["url"], "id": insumo_3d["id"], "vista" : "", "checkbox" : checkbox}
                                    self.array_insumos.append(new_insumo)
                                    print("Se agregó el insumo "+insumo_3d["nombre"]+"-Modelo 3D")
                                
                            for insumo_360 in proyecto["360s"]:
                                if len(self.array_insumos)>0:
                                    if any(insumo["id"] == insumo_360["id"] and insumo["tipo"] == "360" for insumo in self.array_insumos):
                                        print("No se agregó el insumo "+insumo_360["nombre"]+"-360"+" porque ya existe")
                                        continue
                                    else:
                                        checkbox = QCheckBox()
                                        checkbox.setStyleSheet("margin:auto;")
                                        checkbox.stateChanged.connect(self.insumo_seleccionado)
                                        new_insumo = {"nombre": insumo_360["nombre"], "tipo": "360", "fecha": str(datetime.fromisoformat(insumo_360["created_at"].replace("Z", "-05:00"))), "url": insumo_360["url"], "id": insumo_360["id"], "vista": "", "checkbox" : checkbox}
                                        self.array_insumos.append(new_insumo)
                                        print("Se agregó el insumo "+insumo_360["nombre"]+"-360")
                                else:
                                    checkbox = QCheckBox()
                                    checkbox.setStyleSheet("margin:auto;")
                                    checkbox.stateChanged.connect(self.insumo_seleccionado)
                                    new_insumo = {"nombre": insumo_360["nombre"], "tipo": "360", "fecha": str(datetime.fromisoformat(insumo_360["created_at"].replace("Z", "-05:00"))), "url": insumo_360["url"], "id": insumo_360["id"], "vista": "", "checkbox" : checkbox}
                                    self.array_insumos.append(new_insumo)
                                    print("Se agregó el insumo "+insumo_360["nombre"]+"-360")
                            for aoi_sended in proyecto["aois"]:
                                new_aoi ={"nombre": aoi_sended["nombre"], "geometry": aoi_sended["polygon"]}
                                self.array_aoi.append(new_aoi)

                                canvas = self.iface.mapCanvas()
                                geometry_rubber = QgsGeometry.fromWkt(aoi_sended["polygon"])
                                #geometry_rubber = QgsCoordinateTransform(QgsCoordinateReferenceSystem("EPSG:9377"), QgsCoordinateReferenceSystem(self.actual_src), QgsProject.instance()).transform(QgsGeometry.fromWkt(aoi_sended["polygon"]))
                                geometry_rubber.transform(QgsCoordinateTransform(QgsCoordinateReferenceSystem("EPSG:9377"), QgsCoordinateReferenceSystem(self.actual_src), QgsProject.instance()))
                                
                                if not geometry_rubber.isEmpty():
                                    rubber_band = QgsRubberBand(canvas, QgsWkbTypes.PolygonGeometry)
                                    rubber_band.setToGeometry(geometry_rubber, None)
                                    rubber_band.setFillColor(QColor(0, 0, 0, 0))  # Transparent fill
                                    rubber_band.setLineStyle(Qt.DotLine)  # Dotted line style
                                    rubber_band.setStrokeColor(QColor(255, 0, 0, 255))  # Set the stroke color to red
                                    rubber_band.setWidth(2)
                                    rubber_band.hide()

                                    self.array_rubber_bands.append(rubber_band)

                            for xyz_sended in proyecto["xyzs"]:
                                new_xyz ={"nombre": xyz_sended["nombre"], "url": xyz_sended["url"], "zmax": xyz_sended["max_zoom"]}
                                self.array_xyzs.append(new_xyz)
                        
                    if self.ui_confuration_active:
                        self.dlg.buttonVerificar.setEnabled(True)
                        self.dlg.lineEditLicencia.setEnabled(True)
                        self.dlg.labelNombreLicencia.setText(license_data["data"]["licencia"]["nombre"])
                        self.dlg.labelCliente.setText(license_data["data"]["licencia"]["cliente"]["nombre"])
                        #TODO: Mejorar semantica duracion licencia
                        days_remaining = (datetime.fromisoformat(license_data["data"]["licencia"]["fecha_fin"]) - datetime.now().astimezone()).days
                        self.dlg.labelDuracionLicencia.setText("Desde "+str(datetime.fromisoformat(license_data["data"]["licencia"]["fecha_inicio"]).date())+" hasta "+str(datetime.fromisoformat(license_data["data"]["licencia"]["fecha_fin"]).date())+". Días restantes: "+str(days_remaining))
                        self.dlg.lineEditLicencia.setText(self.license_key)
                        self.dlg.check360.setEnabled(True)
                        self.dlg.checkModelo_3D.setEnabled(True)
                        self.dlg.checkNubePuntos.setEnabled(True)
                else:
                    print("Licencia invalida")
                    self.iface.messageBar().pushCritical(
                        "Error",
                        license_data["error"],
                    )

                    if os.path.exists(self.license_file):
                        os.remove(self.license_file)
                    if os.path.exists(self.view_configuration_file):
                        os.remove(self.view_configuration_file)
                    
                    if self.ui_confuration_active:
                        print("ui activo")
                        self.dlg.labelNombreLicencia.setText(license_data["error"])
                        self.dlg.labelDuracionLicencia.setText("")
                        self.dlg.check360.setEnabled(False)
                        self.dlg.checkModelo_3D.setEnabled(False)
                        self.dlg.checkNubePuntos.setEnabled(False)
                
            except requests.exceptions.Timeout:
                self.iface.messageBar().pushCritical(
                    "Error",
                    "No se pudo acceder al servidor de GeoKas",
                )
                return
            except requests.RequestException as e:
                print("An error occurred while verifying the license:", e)
        else:
            if self.ui_confuration_active:
                self.dlg.labelNombreLicencia.setText("Sin licencia")
                self.dlg.labelDuracionLicencia.setText("")
                self.dlg.lineEditLicencia.setText("")
                self.dlg.check360.setEnabled(False)
                self.dlg.checkModelo_3D.setEnabled(False)

        nombres_aoi = [aoi["nombre"] for aoi in self.array_aoi]
        self.combo_box.clear()
        self.combo_box.addItems(nombres_aoi)

        nombres_xyz = [xyz["nombre"] for xyz in self.array_xyzs]
        self.combo_box2.clear()
        self.combo_box2.addItems(nombres_xyz)

        if self.ui_confuration_active:
            self.dlg.buttonVerificar.setEnabled(True)
            self.dlg.lineEditLicencia.setEnabled(True)
            self.dlg.repaint()
    
    def insumo_seleccionado(self, state):
        row = self.dlg.tableInsumos.indexAt(self.dlg.tableInsumos.sender().pos()).row()
        print("Insumo seleccionado "+self.array_insumos[row]["nombre"]+"-"+self.array_insumos[row]["tipo"])

        if os.path.exists(self.view_configuration_file):
            with open(self.view_configuration_file, 'r') as file:
                lines = file.readlines()

            with open(self.view_configuration_file, 'w') as file:
                for line in lines:
                    if not line.startswith(str(str(self.array_insumos[row]['id'])+"-"+self.array_insumos[row]['tipo'])):
                        file.write(line)
            with open(self.view_configuration_file, 'a') as file:
                if state == 2:
                    file.write(f"{str(self.array_insumos[row]['id'])}-{self.array_insumos[row]['tipo']}: Active\n")
                else:
                    #print("Va a cerrar una vista, el valor de hasattr es "+str(hasattr(self, self.array_insumos[row]["vista"])))
                    if self.array_insumos[row]["vista"] is not None and self.array_insumos[row]["vista"] != "":
                        print("Cerrando vista de "+self.array_insumos[row]["nombre"]+"-"+self.array_insumos[row]["tipo"])
                        self.iface.mainWindow().removeDockWidget(self.array_insumos[row]["vista"])
                        self.array_insumos[row]["vista"].close()
                        self.array_insumos[row]["vista"].deleteLater()
                        self.array_insumos[row]["vista"].repaint()
                        self.array_insumos[row]["vista"] = None
                        self.iface.mainWindow().repaint()
                    file.write(f"{str(self.array_insumos[row]['id'])}-{self.array_insumos[row]['tipo']}: Inactive\n")
        else:
            with open(self.view_configuration_file, 'w') as file:
                if state == 2:
                    file.write(f"{str(self.array_insumos[row]['id'])}-{self.array_insumos[row]['tipo']}: Active\n")
                else:
                    if self.array_insumos[row]["vista"] is not None and self.array_insumos[row]["vista"] != "":
                        self.iface.mainWindow().removeDockWidget(self.array_insumos[row]["vista"])
                        self.array_insumos[row]["vista"].close()
                        self.array_insumos[row]["vista"].deleteLater()
                        self.array_insumos[row]["vista"].repaint()
                        self.array_insumos[row]["vista"] = None
                        self.iface.mainWindow().repaint()
                    file.write(f"{str(self.array_insumos[row]['id'])}-{self.array_insumos[row]['tipo']}: Inactive\n")

    def configure(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        if not hasattr(self, 'dlg') or self.dlg is None:
            self.dlg = GeoKasInsumosDialog()


        self.dlg.lineEditLicencia.textChanged.connect(self.on_license_changed)
        self.dlg.buttonVerificar.clicked.connect(self.button_verificar_clicked)

        self.dlg.tableInsumos.clearContents()
        self.dlg.tableInsumos.setRowCount(0)
        self.dlg.tableInsumos.setColumnCount(4)

        # Create a provisional array to save the "nombres" that are active
        active_id = []

        # Check the view_configuration_file for active items
        if os.path.exists(self.view_configuration_file):
            with open(self.view_configuration_file, 'r') as file:
                for line in file:
                    if "Active" in line:
                        active_id.append(line.split(":")[0].strip())
        print(active_id)

        self.checkbox_references.clear()  # Clear old references to avoid memory leaks

        for index, insumo in enumerate(self.array_insumos):
            self.dlg.tableInsumos.insertRow(index)
            key_id_tipo = str(insumo["id"]) + "-" + insumo["tipo"]
            print("Creando la tabla para el insumo " + insumo["nombre"] + "-" + insumo["tipo"])

            checkbox = QCheckBox()  # Create a new QCheckBox
            checkbox.setStyleSheet("margin:auto;")
            checkbox.stateChanged.connect(self.insumo_seleccionado)
            self.checkbox_references.append(checkbox)  # Store reference to prevent deletion

            if key_id_tipo in active_id:
                checkbox.setChecked(True)
            else:
                checkbox.setChecked(False)

            self.dlg.tableInsumos.setCellWidget(index, 0, checkbox)
            self.dlg.tableInsumos.setItem(index, 1, QTableWidgetItem(insumo["nombre"]))
            self.dlg.tableInsumos.setItem(index, 2, QTableWidgetItem(insumo["tipo"]))
            self.dlg.tableInsumos.setItem(index, 3, QTableWidgetItem(insumo["fecha"]))

        

        self.ui_confuration_active = True
        
        print("Cantidad de insumos antes de check license en configuracion: "+str(len(self.array_insumos)))
        self.check_license()
        print("Cantidad de insumos Despues de check license en configuracion: "+str(len(self.array_insumos))+"\n\n\n")

        # show the dialog
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        
        # if result:
        #     # Create a text file with the information of the active checkboxes
        #     with open(self.view_configuration_file, 'w') as file:
        #         if self.dlg.check360.isChecked():
        #             file.write("360: Active\n")
        #         else:
        #             file.write("360: Inactive\n")

        #         if self.dlg.checkModelo_3D.isChecked():
        #             file.write("3D: Active\n")
        #         else:
        #             file.write("3D: Inactive\n")

        #         if self.dlg.checkNubePuntos.isChecked():
        #             file.write("Point_Cloud: Active\n")
        #         else:
        #             file.write("Point_Cloud: Inactive\n")
        #     pass

class PointTool(QgsMapTool):
    def __init__(self, iface, canvas, url_base, token, array_insumos, array_ruber_bands, json_response):
        self.iface = iface
        QgsMapTool.__init__(self, canvas)
        self.canvas = canvas
        self.url_base = url_base
        self.token = token
        self.array_insumos = array_insumos
        self.array_ruber_bands = array_ruber_bands
        self.json_response = json_response

    def canvasPressEvent(self, event):
        x = event.pos().x()
        y = event.pos().y()
        global rb, premuto, point0
        if not premuto: 
            premuto = True
            rb = QgsRubberBand(iface.mapCanvas(), QgsWkbTypes.PointGeometry)
            rb.setColor(QtCore.Qt.red)
            point0 = self.canvas.getCoordinateTransform().toMapCoordinates(x, y)
            rb.addPoint(point0)

    def canvasMoveEvent(self, event):
        x = event.pos().x()
        y = event.pos().y()        
        global premuto, point0, point1, linea, rl
        if premuto:
            if not linea:              
                rl.setColor(QtCore.Qt.red)
                point1 = self.canvas.getCoordinateTransform().toMapCoordinates(x, y)
                rl.addPoint(point0)  
                rl.addPoint(point1)
                linea = True
            else:
                if linea: 
                    point1 = self.canvas.getCoordinateTransform().toMapCoordinates(x, y)
                    rl.reset(QgsWkbTypes.LineGeometry)
                    rl.addPoint(point0)  
                    rl.addPoint(point1)

    def canvasReleaseEvent(self, event):
        global premuto, linea, rb, rl, point1, point0
        premuto = False
        linea = False
        actual_crs = self.canvas.mapSettings().destinationCrs()
        crsDest2 = QgsCoordinateReferenceSystem('EPSG:9377')  # Origen Nacional
        xform = QgsCoordinateTransform(actual_crs, crsDest2, QgsProject.instance())
        pt1 = xform.transform(point0)

        url_restante_3d = "/api/plugins/insumos/tresd-url-generate?token="

        #print("Punto capturado: " + str(point0) + " en sistema de coordenadas " + str(actual_crs))
        print("Punto capturado: " + str(point1) + " en sistema de coordenadas " + str(crsDest2))

        print("Insumos: "+str(self.array_insumos))

        for i in range(len(self.json_response["data"]["licencia"]["proyectos"])):
            geometry_aoi = QgsGeometry.fromWkt(self.json_response["data"]["licencia"]["proyectos"][i]["aois"][0]["polygon"])
            if not geometry_aoi.isEmpty():
                #print("Geometry created successfully")
                geometry_aoi.transform(QgsCoordinateTransform(QgsCoordinateReferenceSystem("EPSG:9377"), QgsCoordinateReferenceSystem(actual_crs), QgsProject.instance()))
                if geometry_aoi.contains(QgsPointXY(pt1.x(), pt1.y())) and self.json_response["data"]["licencia"]["proyectos"][i]["3ds"] != []:
                    print("El punto está dentro del AOI "+self.json_response["data"]["licencia"]["proyectos"][i]["nombre"])
                    try:
                        datos_query = "&id="+str(self.json_response["data"]["licencia"]["proyectos"][i]["3ds"][0]["id"])+"&x="+str(pt1.x())+"&y="+str(pt1.y())+"&src=9377"
                        print("Iniciando request "+str(self.url_base + url_restante_3d + self.token + datos_query))
                        response = requests.get(self.url_base + url_restante_3d + self.token+ datos_query, timeout=60)
                        tresd_data = response.json()
                        print("Response: "+str(tresd_data))
                        #FIXME: Solucionar cuando no hay servidor activo
                        if response.status_code == 200:

                            for j in range(len(self.array_insumos)):
                                if self.array_insumos[j]["id"] == self.json_response["data"]["licencia"]["proyectos"][i]["3ds"][0]["id"]:
                                    if self.array_insumos[j]["vista"] == "" or self.array_insumos[j]["vista"] is None:
                                        self.array_insumos[j]["vista"] = GeoKasInsumosDockableDialog2()
                                        self.array_insumos[j]["vista"].setWindowTitle(self.array_insumos[j]["nombre"] + " - " + self.array_insumos[j]["tipo"])

                                    web_view = QWebView()
                                    web_view.setUrl(QUrl(tresd_data["data"]["url"]))

                                    # Remove all widgets from the container before adding a new one
                                    while self.array_insumos[j]["vista"].dialog_widget.contenedor.count() > 0:
                                        widget_to_remove = self.array_insumos[j]["vista"].dialog_widget.contenedor.takeAt(0).widget()
                                        if widget_to_remove is not None:
                                            widget_to_remove.deleteLater()
                                    self.array_insumos[j]["vista"].dialog_widget.contenedor.addWidget(web_view)
                                    self.iface.mainWindow().addDockWidget(Qt.RightDockWidgetArea, self.array_insumos[j]["vista"])
                                    self.array_insumos[j]["vista"].show()

                            if self.array_insumos[i]["vista"] == "" or self.array_insumos[i]["vista"] == None:
                                self.array_insumos[i]["vista"] = GeoKasInsumosDockableDialog2()
                                self.array_insumos[i]["vista"].setWindowTitle(self.array_insumos[i]["nombre"]+" - "+self.array_insumos[i]["tipo"])

                    except requests.exceptions.Timeout:
                        self.iface.messageBar().pushCritical(
                            "Error",
                            "No se pudo acceder al servidor de GeoKas",
                        )
                        return
                    except requests.RequestException as e:
                        print("An error occurred while accessing to 3D Model:", e)
                    


        """

        try:
            response = requests.get(self.url_base + url_restante_3d + self.token, timeout=60)
            tresd_data = response.json()
            #FIXME: Solucionar cuando no hay servidor activo
            if response.status_code == 200:
                self.dock_widget.tresd_data["data"]["url"]

                web_view = QWebView()
                web_view.setUrl(QUrl(tresd_data["data"]["url"]))
                # Remove all widgets from the container before adding a new one
                while self.dock_widget.dialog_widget.contenedor.count() > 0:
                    widget_to_remove = self.dock_widget.dialog_widget.contenedor.takeAt(0).widget()
                    if widget_to_remove is not None:
                        widget_to_remove.deleteLater()
                # Add the new widget
                self.dock_widget.dialog_widget.contenedor.addWidget(web_view)

        except requests.exceptions.Timeout:
            self.iface.messageBar().pushCritical(
                "Error",
                "No se pudo acceder al servidor de GeoKas",
            )
            return
        except requests.RequestException as e:
            print("An error occurred while accessing to 3D Model:", e)
        
        iface.messageBar().pushCritical(
            "Resultado",
            "La zona seleccionada no tiene un gemelo digital capturado en GeoKas.",
        )"
        """
        rl.reset()
        rb.reset()           
        self.canvas.unsetMapTool(self)

    def activate(self):
        pass

    def deactivate(self):
        pass
       
    def isZoomTool(self):
        return False

    def isTransient(self):
        return False

    def isEditTool(self):
        return True

        